#!/bin/bash

export File_PDB_Mesra_Rewards_FAQ='File_PDB_SmartPay_Question_1Cx_Zjm438b93b3'
export File_PDB_Shop_FAQ='File_PDB_Petronas_Shop_Question_1Cx_Zjm1dd9fb28'
export File_PDB_SmartPay_FAQ='File_PDB_NGV_Question_1Cx_Zjmf9ece1cd'
export File_PDB_Giftcard_FAQ='File_PDB_Giftcard_Question_1Cx_Zjmb9409d59'
export File_PDB_NGV_FAQ='File_PDB_Mesra_Rewards_Question_1Cx_Zjmcb00fa86'
export Default_FileUDMO_SI_Retriever='Default_FileUDMO_SI_Retriever_1Cx_Zjm066fc325'
export AgentuserREPLACE='petronas_service_agent@00dh10000003zwp1.ext'
export BotuserREPLACE='nurazlini.ammar@petronas.com.my.agentforce'